tokenizer:
  model_name: ThaiKami/bartpho-word-BA-fix-001
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: False

reward_fn:
  id: fixdate

datapool:
  id: vi_sum
  args:
    n_samples: 50

env:
  n_envs: 10
  args:
    max_prompt_length: 512
    max_episode_length: 250
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 512
    batch_size: 4
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    ent_coef: 0.0
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: ThaiKami/bartpho-word-BA-fix-001
      apply_model_parallel: False
      prompt_truncation_side: "right"
      generation_kwargs:
        num_beams: 4
        max_length: 250
        min_length: 100

train_evaluation:
  eval_batch_size: 100
  n_iters: 100
  eval_every: 10
  save_every: 1
  metrics:
    - id: rouge
  
  generation_kwargs: 
    num_beams: 4
    max_length: 250
    min_length: 100
